name: CD (Dokku)

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v3.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        HOST: scarinci.dev
        PROJECT: martino-bot